'use client'

import { useCallback } from 'react'
import { useLanguageContext } from '@/contexts/language-context'

type Language = 'es' | 'en'

const translations = {
  es: {
    'title': 'Anclora Press',
    'subtitle': 'Plataforma de Publishing Digital',
    'tagline': 'Tu productividad, bien anclada',
    'editor.title': 'Editor Avanzado',
    'editor.description': 'Herramientas profesionales para edición de contenido',
    'import.title': 'Importar Documento',
    'import.description': 'Importa contenido desde archivos existentes en el editor avanzado',
    'import.select': 'Seleccionar Archivo',
    'import.uploading': 'Importando documento...',
    'import.processing': 'Procesando el contenido del documento...',
    'import.dragdrop': 'Arrastra un archivo aquí o haz clic para seleccionar',
    'search.placeholder': 'Texto a buscar...',
    'replace.placeholder': 'Texto de reemplazo...',
    'search.button': 'Buscar',
    'replace.button': 'Reemplazar',
    'undo.title': 'Deshacer',
    'redo.title': 'Rehacer',
    'step.content.title': 'Contenido',
    'step.content.description': 'Escribe y estructura tu contenido',
    'step.chapters.title': 'Capítulos',
    'step.chapters.description': 'Organiza tu libro en capítulos',
    'step.template.title': 'Plantilla',
    'step.template.description': 'Elige el diseño perfecto',
    'step.cover.title': 'Portada',
    'step.cover.description': 'Diseña una portada atractiva',
    'step.backcover.title': 'Contraportada',
    'step.backcover.description': 'Añade información y reseñas',
    'step.preview.title': 'Vista Previa',
    'step.preview.description': 'Revisa tu libro antes de publicar',
    'step.collaborate.title': 'Colaborar',
    'step.collaborate.description': 'Trabaja en equipo con otros',
    'step.ai.title': 'IA',
    'step.ai.description': 'Mejora tu contenido con IA',
    'step.export.title': 'Exportar',
    'step.export.description': 'Publica en múltiples formatos',
    'button.previous': 'Anterior',
    'button.next': 'Siguiente',
    'button.save': 'Guardar',
    'button.preview': 'Vista Previa',
    'button.export': 'Exportar',
    'progress.title': 'Progreso del Libro',
    'progress.step': 'Paso',
    'progress.of': 'de',
    'preview.title': 'Vista Previa del Libro',
    'preview.subtitle': 'Revisa cómo se verá tu libro antes de publicarlo',
    'preview.button': 'Abrir Vista Previa',
    'export.title': 'Exportar tu libro',
    'export.subtitle': 'Tu libro está listo para ser exportado en diferentes formatos',
    'export.pdf': 'Formato ideal para impresión',
    'export.epub': 'Formato estándar para ebooks',
    'editor.basic': 'Básico',
    'editor.advanced': 'Avanzado',
  },
  en: {
    'title': 'Anclora Press',
    'subtitle': 'Digital Publishing Platform',
    'tagline': 'Your productivity, well anchored',
    'editor.title': 'Advanced Editor',
    'editor.description': 'Professional content editing tools',
    'import.title': 'Import Document',
    'import.description': 'Import content from existing files in the advanced editor',
    'import.select': 'Select File',
    'import.uploading': 'Importing document...',
    'import.processing': 'Processing document content...',
    'import.dragdrop': 'Drag a file here or click to select',
    'search.placeholder': 'Search text...',
    'replace.placeholder': 'Replacement text...',
    'search.button': 'Search',
    'replace.button': 'Replace',
    'undo.title': 'Undo',
    'redo.title': 'Redo',
    'step.content.title': 'Content',
    'step.content.description': 'Write and structure your content',
    'step.chapters.title': 'Chapters',
    'step.chapters.description': 'Organize your book into chapters',
    'step.template.title': 'Template',
    'step.template.description': 'Choose the perfect design',
    'step.cover.title': 'Cover',
    'step.cover.description': 'Design an attractive cover',
    'step.backcover.title': 'Back Cover',
    'step.backcover.description': 'Add information and reviews',
    'step.preview.title': 'Preview',
    'step.preview.description': 'Review your book before publishing',
    'step.collaborate.title': 'Collaborate',
    'step.collaborate.description': 'Work as a team with others',
    'step.ai.title': 'AI',
    'step.ai.description': 'Improve your content with AI',
    'step.export.title': 'Export',
    'step.export.description': 'Publish in multiple formats',
    'button.previous': 'Previous',
    'button.next': 'Next',
    'button.save': 'Save',
    'button.preview': 'Preview',
    'button.export': 'Export',
    'progress.title': 'Book Progress',
    'progress.step': 'Step',
    'progress.of': 'of',
    'preview.title': 'Book Preview',
    'preview.subtitle': 'Review how your book will look before publishing',
    'preview.button': 'Open Preview',
    'export.title': 'Export your book',
    'export.subtitle': 'Your book is ready to be exported in different formats',
    'export.pdf': 'Ideal format for printing',
    'export.epub': 'Standard format for ebooks',
    'editor.basic': 'Basic',
    'editor.advanced': 'Advanced',
  },
}

export function useLanguage() {
  const { language, mounted } = useLanguageContext()

  const t = useCallback(
    (key: string, defaultValue?: string): string => {
      if (!mounted) return defaultValue || key
      const translation = translations[language as Language][key as keyof typeof translations['es']]
      return translation || defaultValue || key
    },
    [language, mounted]
  )

  return { language, t, mounted }
}
