'use client'

import { useCallback } from 'react'
import { useLanguageContext } from '@/contexts/language-context'

type Language = 'es' | 'en'

const translations = {
  es: {
    'title': 'Anclora Press',
    'subtitle': 'Plataforma de Publishing Digital',
    'tagline': 'Tu productividad, bien anclada',
    'editor.title': 'Editor Avanzado',
    'editor.description': 'Herramientas profesionales para edición de contenido',
    'import.title': 'Importar Documento',
    'import.description': 'Importa contenido desde archivos existentes en el editor avanzado',
    'import.select': 'Seleccionar Archivo',
    'import.uploading': 'Importando documento...',
    'import.processing': 'Procesando el contenido del documento...',
    'import.dragdrop': 'Arrastra un archivo aquí o haz clic para seleccionar',
    'search.placeholder': 'Texto a buscar...',
    'replace.placeholder': 'Texto de reemplazo...',
    'search.button': 'Buscar',
    'replace.button': 'Reemplazar',
    'undo.title': 'Deshacer',
    'redo.title': 'Rehacer',
    'step.content.title': 'Contenido',
    'step.content.description': 'Escribe y estructura tu contenido',
    'step.chapters.title': 'Capítulos',
    'step.chapters.description': 'Organiza tu libro en capítulos',
    'step.template.title': 'Plantilla',
    'step.template.description': 'Elige el diseño perfecto',
    'step.cover.title': 'Portada',
    'step.cover.description': 'Diseña una portada atractiva',
    'step.backcover.title': 'Contraportada',
    'step.backcover.description': 'Añade información y reseñas',
    'step.preview.title': 'Vista Previa',
    'step.preview.description': 'Revisa tu libro antes de publicar',
    'step.collaborate.title': 'Colaborar',
    'step.collaborate.description': 'Trabaja en equipo con otros',
    'step.ai.title': 'IA',
    'step.ai.description': 'Mejora tu contenido con IA',
    'step.export.title': 'Exportar',
    'step.export.description': 'Publica en múltiples formatos',
    'button.previous': 'Anterior',
    'button.next': 'Siguiente',
    'button.save': 'Guardar',
    'button.preview': 'Vista Previa',
    'button.export': 'Exportar',
    'progress.title': 'Progreso del Libro',
    'progress.step': 'Paso',
    'progress.of': 'de',
    'preview.title': 'Vista Previa del Libro',
    'preview.subtitle': 'Revisa cómo se verá tu libro antes de publicarlo',
    'preview.button': 'Abrir Vista Previa',
    'export.title': 'Exportar tu libro',
    'export.subtitle': 'Tu libro está listo para ser exportado en diferentes formatos',
    'export.pdf': 'Formato ideal para impresión',
    'export.epub': 'Formato estándar para ebooks',
    'editor.basic': 'Básico',
    'editor.advanced': 'Avanzado',
    // Text Editor
    'texteditor.title': 'Información del Libro',
    'texteditor.subtitle': 'Añade los detalles básicos de tu libro',
    'texteditor.bookTitle': 'Título *',
    'texteditor.bookTitlePlaceholder': 'El título de tu libro',
    'texteditor.author': 'Autor *',
    'texteditor.authorPlaceholder': 'Tu nombre',
    'texteditor.bookSubtitle': 'Subtítulo (opcional)',
    'texteditor.bookSubtitlePlaceholder': 'Un subtítulo descriptivo',
    'texteditor.content': 'Contenido del Libro',
    'texteditor.contentDescription': 'Escribe el contenido de tu libro usando formato Markdown',
    'texteditor.words': 'palabras',
    'texteditor.characters': 'caracteres',
    'texteditor.bold': 'Negrita',
    'texteditor.italic': 'Cursiva',
    'texteditor.title': 'Título',
    'texteditor.unorderedList': 'Lista desordenada',
    'texteditor.orderedList': 'Lista ordenada',
    'texteditor.quote': 'Cita',
    'texteditor.link': 'Enlace',
    'texteditor.image': 'Imagen',
    'texteditor.importLimits': 'Límites de Importación',
    'texteditor.maxPages': 'Máx. 300',
    'texteditor.maxSize': 'Máx. 50MB',
    'texteditor.supportedFormats': '8 soportados',
    'texteditor.formatsSupported': 'Formatos soportados:',
    'texteditor.tipsBetter': 'Consejos para escribir mejor',
    'texteditor.minimumContent': 'Para continuar, asegúrate de tener al menos 100 caracteres de contenido, un título y un autor.',
    'texteditor.importSuccess': 'Documento "${filename}" importado y cargado como contenido principal',
    'texteditor.importAppended': 'Documento "${filename}" añadido al contenido existente',
    'texteditor.importError': 'Error al importar el documento',
    'texteditor.importConnectionError': 'Error de conexión al importar el documento',
    'texteditor.plainText': 'Texto plano',
    'texteditor.word97': 'Word 97-2003',
    'texteditor.word2007': 'Word 2007+',
    'texteditor.richText': 'Rich Text',
    'texteditor.openDocument': 'OpenDocument',
    'texteditor.ebook': 'eBook',
    // Chapter Editor
    'chapter.title': 'Editor de Capítulos',
    'chapter.subtitle': 'Organiza tu libro en capítulos coherentes y estructurados',
    'chapter.chapters': 'Capítulos',
    'chapter.chaptersCount': '${count} capítulos • ${words} palabras',
    'chapter.import': 'Importar',
    'chapter.importDialog': 'Importar Capítulo',
    'chapter.chapterTitle': 'Título del capítulo',
    'chapter.chapterTitlePlaceholder': 'Título del capítulo importado',
    'chapter.content': 'Contenido',
    'chapter.contentPlaceholder': 'Pega el contenido del capítulo aquí...',
    'chapter.cancel': 'Cancelar',
    'chapter.search': 'Buscar capítulos...',
    'chapter.filterStatus': 'Filtrar por estado',
    'chapter.draft': 'Borrador',
    'chapter.completed': 'Completado',
    'chapter.reviewed': 'Revisado',
    'chapter.empty': 'No hay capítulos aún',
    'chapter.emptySubtitle': 'Crea tu primer capítulo para comenzar a estructurar tu libro',
    'chapter.words': 'palabras',
    'chapter.duplicate': 'Duplicar capítulo',
    'chapter.delete': 'Eliminar capítulo',
    'chapter.newChapterTitle': 'Título del nuevo capítulo...',
    'chapter.addChapter': 'Añadir Capítulo',
    'chapter.editing': 'Editando',
    'chapter.chapterInfo': 'Capítulo ${order} • ${wordCount} palabras',
    'chapter.save': 'Guardar',
    'chapter.chapterTitleLabel': 'Título del Capítulo',
    'chapter.chapterContentLabel': 'Contenido del Capítulo',
    'chapter.chapterContentPlaceholder': 'Escribe el contenido de este capítulo...',
    'chapter.lastModified': 'Última modificación: ${date}',
    'chapter.selectChapter': 'Selecciona un Capítulo',
    'chapter.selectChapterDesc': 'Selecciona o crea un capítulo para empezar a editar',
    'chapter.createChapter': 'O crea un nuevo capítulo usando el formulario de la izquierda',
    'chapter.totalChapters': 'Total Capítulos',
    'chapter.completedCount': 'Completados',
    'chapter.draftsCount': 'Borradores',
    'chapter.totalWords': 'Palabras Totales',
    // Template Gallery
    'template.title': 'Elige la Plantilla Perfecta',
    'template.subtitle': 'Selecciona un diseño que se ajuste al estilo de tu libro',
    'template.modern': 'Moderno',
    'template.modernDesc': 'Diseño limpio y minimalista perfecto para libros técnicos y de negocios',
    'template.classic': 'Clásico',
    'template.classicDesc': 'Estilo atemporal ideal para novelas y literatura',
    'template.creative': 'Creativo',
    'template.creativeDesc': 'Diseño audaz para libros de arte y fotografía',
    'template.academic': 'Académico',
    'template.academicDesc': 'Formato riguroso para tesis y papers académicos',
    'template.magazine': 'Revista',
    'template.magazineDesc': 'Estilo de revista para publicaciones periódicas',
    'template.minimal': 'Minimalista',
    'template.minimalDesc': 'Diseño ultra-simple para máxima legibilidad',
    'template.all': 'Todas',
    'template.professional': 'Profesional',
    'template.literature': 'Literatura',
    'template.creative': 'Creativo',
    'template.academic': 'Académico',
    'template.editorial': 'Editorial',
    'template.minimalist': 'Minimalista',
    'template.custom': 'Personalizada',
    'template.preview': 'Vista Previa',
    'template.features': 'Características:',
    'template.view': 'Vista',
    'template.select': 'Seleccionada',
    'template.createCustom': 'Crea tu Propia Plantilla',
    'template.createCustomDesc': 'Diseña una plantilla personalizada basada en tus preferencias',
    'template.createTemplate': 'Crear Plantilla Personalizada',
    'template.basePlates': 'Plantillas Base',
    'template.customPlates': 'Personalizadas',
    'template.categories': 'Categorías',
    'template.possibilities': 'Posibilidades',
    'template.previewTemplate': 'Vista previa de la plantilla',
    'template.selectTemplate': 'Seleccionar Plantilla',
    // Cover Editor
    'cover.title': 'Diseña tu Portada',
    'cover.subtitle': 'Crea una portada profesional que atrapea a los lectores',
    'cover.preview': 'Vista Previa',
    'cover.generating': 'Generando...',
    'cover.generateAI': 'Generar con IA',
    'cover.export': 'Exportar',
    'cover.yourTitle': 'Tu Título Aquí',
    'cover.yourName': 'Tu Nombre',
    'cover.backgroundColor': 'Color de Fondo',
    'cover.backgroundColorDesc': 'Elige un color que represente el tono de tu libro',
    'cover.customColor': 'Color Personalizado',
    'cover.backgroundImage': 'Imagen de Fondo',
    'cover.backgroundImageDesc': 'Añade una imagen para hacer tu portada más visual',
    'cover.uploadImage': 'Subir imagen',
    'cover.currentImage': 'Imagen Actual',
    'cover.remove': 'Eliminar',
    'cover.typography': 'Tipografía',
    'cover.typographyDesc': 'Elige la fuente perfecta para tu portada',
    'cover.textExample': 'Ejemplo de Texto',
    'cover.design': 'Diseño',
    'cover.designDesc': 'Organiza los elementos en tu portada',
    'cover.minimumRequired': 'Para continuar, asegúrate de tener un título y un autor definidos.',
    // Export Modal
    'export.title': 'Exportar tu Libro',
    'export.subtitle': 'Elige el formato y opciones para exportar tu libro',
    'export.format': 'Formato de Exportación',
    'export.quality': 'Calidad de Exportación',
    'export.standard': 'Estándar',
    'export.high': 'Alta',
    'export.print': 'Impresión',
    'export.options': 'Opciones Adicionales',
    'export.includeCover': 'Incluir portada',
    'export.tableOfContents': 'Generar tabla de contenidos',
    'export.pageNumbers': 'Incluir números de página',
    'export.metadata': 'Incluir metadatos (autor, título, etc.)',
    'export.bookInfo': 'Información del Libro',
    'export.words': 'Palabras',
    'export.exporting': 'Exportando...',
    'export.progress': 'Progreso',
    'export.completed': '¡Exportación Completada!',
    'export.completedDesc': 'Tu libro ha sido exportado exitosamente en formato ${format}.',
    'export.download': 'Descargar',
    'export.share': 'Compartir',
    'export.compatibility': 'Compatibilidad',
    'export.mobiles': 'Móviles y tablets',
    'export.computers': 'Computadoras',
    'export.ereaders': 'E-readers',
    'export.cancel': 'Cancelar',
    // AI Copilot
    'ai.title': 'IA Copilot',
    'ai.subtitle': 'Mejora tu contenido con sugerencias inteligentes',
    'ai.tools': 'Herramientas IA',
    'ai.selectTool': 'Selecciona una herramienta para mejorar tu libro',
    'ai.customQuery': 'Consulta Personalizada',
    'ai.customQueryDesc': 'Pide cualquier mejora o sugerencia específica',
    'ai.yourQuery': 'Tu consulta',
    'ai.queryPlaceholder': 'Ej: ¿Cómo puedo hacer la introducción más interesante?',
    'ai.send': 'Enviar Consulta',
    'ai.recentSuggestions': 'Sugerencias Recientes',
    'ai.suggestionsCount': 'sugerencias',
    'ai.noSuggestions': 'Sin Sugerencias',
    'ai.noSuggestionsDesc': 'Selecciona una herramienta para generar sugerencias personalizadas',
    'ai.generating': 'Generando...',
    'ai.applied': 'Aplicada',
    'ai.apply': 'Aplicar',
    'ai.copy': 'Copiar',
    'ai.useful': '¿Útil?',
    'ai.generatedSuggestions': 'Sugerencias Generadas',
    'ai.appliedCount': 'Aplicadas',
    'ai.positiveFeedback': 'Feedback Positivo',
    // Collaboration Panel
    'collab.title': 'Colaboración',
    'collab.subtitle': 'Trabaja en equipo y gestiona comentarios de forma eficiente',
    'collab.team': 'Equipo de Trabajo',
    'collab.teamCount': '${count} colaboradores en este proyecto',
    'collab.invite': 'Invitar',
    'collab.owner': 'Propietario',
    'collab.editor': 'Editor',
    'collab.commenter': 'Comentarista',
    'collab.online': 'En línea',
    'collab.offline': 'Sin conexión',
    'collab.addComment': 'Añadir Comentario',
    'collab.yourComment': 'Tu comentario',
    'collab.commentPlaceholder': 'Añade un comentario sobre el contenido...',
    'collab.comments': 'Comentarios',
    'collab.commentsCount': '${count} comentarios',
    'collab.searchComments': 'Buscar comentarios...',
    'collab.filterAll': 'Todos',
    'collab.filterUnresolved': 'Sin resolver',
    'collab.filterResolved': 'Resueltos',
    'collab.noComments': 'No hay comentarios para mostrar',
    'collab.resolved': 'Resuelto',
    'collab.resolve': 'Resolver',
    'collab.reply': 'Responder',
    'collab.delete': 'Eliminar',
    'collab.replyPlaceholder': 'Escribe tu respuesta...',
    'collab.sendReply': 'Enviar Respuesta',
    'collab.cancel': 'Cancelar',
    'collab.versions': 'Historial de Versiones',
    'collab.versionsDesc': 'Sigue los cambios y vuelve a versiones anteriores',
    'collab.revert': 'Revertir',
    'collab.added': '+${count} añadidos',
    'collab.removed': '-${count} eliminados',
    'collab.modified': '${count} modificados',
    'collab.collaborators': 'Colaboradores',
    'collab.pendingComments': 'Comentarios Pendientes',
    'collab.resolvedComments': 'Comentarios Resueltos',
  },
  en: {
    'title': 'Anclora Press',
    'subtitle': 'Digital Publishing Platform',
    'tagline': 'Your productivity, well anchored',
    'editor.title': 'Advanced Editor',
    'editor.description': 'Professional content editing tools',
    'import.title': 'Import Document',
    'import.description': 'Import content from existing files in the advanced editor',
    'import.select': 'Select File',
    'import.uploading': 'Importing document...',
    'import.processing': 'Processing document content...',
    'import.dragdrop': 'Drag a file here or click to select',
    'search.placeholder': 'Search text...',
    'replace.placeholder': 'Replacement text...',
    'search.button': 'Search',
    'replace.button': 'Replace',
    'undo.title': 'Undo',
    'redo.title': 'Redo',
    'step.content.title': 'Content',
    'step.content.description': 'Write and structure your content',
    'step.chapters.title': 'Chapters',
    'step.chapters.description': 'Organize your book into chapters',
    'step.template.title': 'Template',
    'step.template.description': 'Choose the perfect design',
    'step.cover.title': 'Cover',
    'step.cover.description': 'Design an attractive cover',
    'step.backcover.title': 'Back Cover',
    'step.backcover.description': 'Add information and reviews',
    'step.preview.title': 'Preview',
    'step.preview.description': 'Review your book before publishing',
    'step.collaborate.title': 'Collaborate',
    'step.collaborate.description': 'Work as a team with others',
    'step.ai.title': 'AI',
    'step.ai.description': 'Improve your content with AI',
    'step.export.title': 'Export',
    'step.export.description': 'Publish in multiple formats',
    'button.previous': 'Previous',
    'button.next': 'Next',
    'button.save': 'Save',
    'button.preview': 'Preview',
    'button.export': 'Export',
    'progress.title': 'Book Progress',
    'progress.step': 'Step',
    'progress.of': 'of',
    'preview.title': 'Book Preview',
    'preview.subtitle': 'Review how your book will look before publishing',
    'preview.button': 'Open Preview',
    'export.title': 'Export your book',
    'export.subtitle': 'Your book is ready to be exported in different formats',
    'export.pdf': 'Ideal format for printing',
    'export.epub': 'Standard format for ebooks',
    'editor.basic': 'Basic',
    'editor.advanced': 'Advanced',
    // Text Editor
    'texteditor.title': 'Book Information',
    'texteditor.subtitle': 'Add the basic details of your book',
    'texteditor.bookTitle': 'Title *',
    'texteditor.bookTitlePlaceholder': 'Your book title',
    'texteditor.author': 'Author *',
    'texteditor.authorPlaceholder': 'Your name',
    'texteditor.bookSubtitle': 'Subtitle (optional)',
    'texteditor.bookSubtitlePlaceholder': 'A descriptive subtitle',
    'texteditor.content': 'Book Content',
    'texteditor.contentDescription': 'Write the content of your book using Markdown format',
    'texteditor.words': 'words',
    'texteditor.characters': 'characters',
    'texteditor.bold': 'Bold',
    'texteditor.italic': 'Italic',
    'texteditor.title': 'Title',
    'texteditor.unorderedList': 'Unordered list',
    'texteditor.orderedList': 'Ordered list',
    'texteditor.quote': 'Quote',
    'texteditor.link': 'Link',
    'texteditor.image': 'Image',
    'texteditor.importLimits': 'Import Limits',
    'texteditor.maxPages': 'Max. 300',
    'texteditor.maxSize': 'Max. 50MB',
    'texteditor.supportedFormats': '8 supported',
    'texteditor.formatsSupported': 'Supported formats:',
    'texteditor.tipsBetter': 'Tips for better writing',
    'texteditor.minimumContent': 'To continue, make sure to have at least 100 characters of content, a title, and an author.',
    'texteditor.importSuccess': 'Document "${filename}" imported and loaded as main content',
    'texteditor.importAppended': 'Document "${filename}" added to existing content',
    'texteditor.importError': 'Error importing document',
    'texteditor.importConnectionError': 'Connection error while importing document',
    'texteditor.plainText': 'Plain Text',
    'texteditor.word97': 'Word 97-2003',
    'texteditor.word2007': 'Word 2007+',
    'texteditor.richText': 'Rich Text',
    'texteditor.openDocument': 'OpenDocument',
    'texteditor.ebook': 'eBook',
    // Chapter Editor
    'chapter.title': 'Chapter Editor',
    'chapter.subtitle': 'Organize your book into coherent and structured chapters',
    'chapter.chapters': 'Chapters',
    'chapter.chaptersCount': '${count} chapters • ${words} words',
    'chapter.import': 'Import',
    'chapter.importDialog': 'Import Chapter',
    'chapter.chapterTitle': 'Chapter title',
    'chapter.chapterTitlePlaceholder': 'Imported chapter title',
    'chapter.content': 'Content',
    'chapter.contentPlaceholder': 'Paste the chapter content here...',
    'chapter.cancel': 'Cancel',
    'chapter.search': 'Search chapters...',
    'chapter.filterStatus': 'Filter by status',
    'chapter.draft': 'Draft',
    'chapter.completed': 'Completed',
    'chapter.reviewed': 'Reviewed',
    'chapter.empty': 'No chapters yet',
    'chapter.emptySubtitle': 'Create your first chapter to start structuring your book',
    'chapter.words': 'words',
    'chapter.duplicate': 'Duplicate chapter',
    'chapter.delete': 'Delete chapter',
    'chapter.newChapterTitle': 'New chapter title...',
    'chapter.addChapter': 'Add Chapter',
    'chapter.editing': 'Editing',
    'chapter.chapterInfo': 'Chapter ${order} • ${wordCount} words',
    'chapter.save': 'Save',
    'chapter.chapterTitleLabel': 'Chapter Title',
    'chapter.chapterContentLabel': 'Chapter Content',
    'chapter.chapterContentPlaceholder': 'Write the content of this chapter...',
    'chapter.lastModified': 'Last modified: ${date}',
    'chapter.selectChapter': 'Select a Chapter',
    'chapter.selectChapterDesc': 'Select or create a chapter to start editing',
    'chapter.createChapter': 'Or create a new chapter using the form on the left',
    'chapter.totalChapters': 'Total Chapters',
    'chapter.completedCount': 'Completed',
    'chapter.draftsCount': 'Drafts',
    'chapter.totalWords': 'Total Words',
    // Template Gallery
    'template.title': 'Choose the Perfect Template',
    'template.subtitle': 'Select a design that fits the style of your book',
    'template.modern': 'Modern',
    'template.modernDesc': 'Clean and minimalist design perfect for technical and business books',
    'template.classic': 'Classic',
    'template.classicDesc': 'Timeless style ideal for novels and literature',
    'template.creative': 'Creative',
    'template.creativeDesc': 'Bold design for art and photography books',
    'template.academic': 'Academic',
    'template.academicDesc': 'Rigorous format for theses and academic papers',
    'template.magazine': 'Magazine',
    'template.magazineDesc': 'Magazine style for periodical publications',
    'template.minimal': 'Minimal',
    'template.minimalDesc': 'Ultra-simple design for maximum readability',
    'template.all': 'All',
    'template.professional': 'Professional',
    'template.literature': 'Literature',
    'template.creative': 'Creative',
    'template.academic': 'Academic',
    'template.editorial': 'Editorial',
    'template.minimalist': 'Minimalist',
    'template.custom': 'Custom',
    'template.preview': 'Preview',
    'template.features': 'Features:',
    'template.view': 'View',
    'template.select': 'Selected',
    'template.createCustom': 'Create Your Own Template',
    'template.createCustomDesc': 'Design a custom template based on your preferences',
    'template.createTemplate': 'Create Custom Template',
    'template.basePlates': 'Base Templates',
    'template.customPlates': 'Custom',
    'template.categories': 'Categories',
    'template.possibilities': 'Possibilities',
    'template.previewTemplate': 'Template preview',
    'template.selectTemplate': 'Select Template',
    // Cover Editor
    'cover.title': 'Design Your Cover',
    'cover.subtitle': 'Create a professional cover that captivates readers',
    'cover.preview': 'Preview',
    'cover.generating': 'Generating...',
    'cover.generateAI': 'Generate with AI',
    'cover.export': 'Export',
    'cover.yourTitle': 'Your Title Here',
    'cover.yourName': 'Your Name',
    'cover.backgroundColor': 'Background Color',
    'cover.backgroundColorDesc': 'Choose a color that represents the tone of your book',
    'cover.customColor': 'Custom Color',
    'cover.backgroundImage': 'Background Image',
    'cover.backgroundImageDesc': 'Add an image to make your cover more visual',
    'cover.uploadImage': 'Upload image',
    'cover.currentImage': 'Current Image',
    'cover.remove': 'Remove',
    'cover.typography': 'Typography',
    'cover.typographyDesc': 'Choose the perfect font for your cover',
    'cover.textExample': 'Text Example',
    'cover.design': 'Design',
    'cover.designDesc': 'Organize the elements on your cover',
    'cover.minimumRequired': 'To continue, make sure to have a title and an author defined.',
    // Export Modal
    'export.title': 'Export Your Book',
    'export.subtitle': 'Choose the format and options to export your book',
    'export.format': 'Export Format',
    'export.quality': 'Export Quality',
    'export.standard': 'Standard',
    'export.high': 'High',
    'export.print': 'Print',
    'export.options': 'Additional Options',
    'export.includeCover': 'Include cover',
    'export.tableOfContents': 'Generate table of contents',
    'export.pageNumbers': 'Include page numbers',
    'export.metadata': 'Include metadata (author, title, etc.)',
    'export.bookInfo': 'Book Information',
    'export.words': 'Words',
    'export.exporting': 'Exporting...',
    'export.progress': 'Progress',
    'export.completed': 'Export Completed!',
    'export.completedDesc': 'Your book has been successfully exported in ${format} format.',
    'export.download': 'Download',
    'export.share': 'Share',
    'export.compatibility': 'Compatibility',
    'export.mobiles': 'Mobiles and tablets',
    'export.computers': 'Computers',
    'export.ereaders': 'E-readers',
    'export.cancel': 'Cancel',
    // AI Copilot
    'ai.title': 'AI Copilot',
    'ai.subtitle': 'Improve your content with intelligent suggestions',
    'ai.tools': 'AI Tools',
    'ai.selectTool': 'Select a tool to improve your book',
    'ai.customQuery': 'Custom Query',
    'ai.customQueryDesc': 'Ask for any specific improvement or suggestion',
    'ai.yourQuery': 'Your query',
    'ai.queryPlaceholder': 'E.g.: How can I make the introduction more interesting?',
    'ai.send': 'Send Query',
    'ai.recentSuggestions': 'Recent Suggestions',
    'ai.suggestionsCount': 'suggestions',
    'ai.noSuggestions': 'No Suggestions',
    'ai.noSuggestionsDesc': 'Select a tool to generate personalized suggestions',
    'ai.generating': 'Generating...',
    'ai.applied': 'Applied',
    'ai.apply': 'Apply',
    'ai.copy': 'Copy',
    'ai.useful': 'Useful?',
    'ai.generatedSuggestions': 'Generated Suggestions',
    'ai.appliedCount': 'Applied',
    'ai.positiveFeedback': 'Positive Feedback',
    // Collaboration Panel
    'collab.title': 'Collaboration',
    'collab.subtitle': 'Work as a team and manage comments efficiently',
    'collab.team': 'Work Team',
    'collab.teamCount': '${count} collaborators on this project',
    'collab.invite': 'Invite',
    'collab.owner': 'Owner',
    'collab.editor': 'Editor',
    'collab.commenter': 'Commenter',
    'collab.online': 'Online',
    'collab.offline': 'Offline',
    'collab.addComment': 'Add Comment',
    'collab.yourComment': 'Your comment',
    'collab.commentPlaceholder': 'Add a comment about the content...',
    'collab.comments': 'Comments',
    'collab.commentsCount': '${count} comments',
    'collab.searchComments': 'Search comments...',
    'collab.filterAll': 'All',
    'collab.filterUnresolved': 'Unresolved',
    'collab.filterResolved': 'Resolved',
    'collab.noComments': 'No comments to show',
    'collab.resolved': 'Resolved',
    'collab.resolve': 'Resolve',
    'collab.reply': 'Reply',
    'collab.delete': 'Delete',
    'collab.replyPlaceholder': 'Write your reply...',
    'collab.sendReply': 'Send Reply',
    'collab.cancel': 'Cancel',
    'collab.versions': 'Version History',
    'collab.versionsDesc': 'Track changes and revert to previous versions',
    'collab.revert': 'Revert',
    'collab.added': '+${count} added',
    'collab.removed': '-${count} removed',
    'collab.modified': '${count} modified',
    'collab.collaborators': 'Collaborators',
    'collab.pendingComments': 'Pending Comments',
    'collab.resolvedComments': 'Resolved Comments',
  },
}

export function useLanguage() {
  const { language, mounted } = useLanguageContext()

  const t = useCallback(
    (key: string, defaultValue?: string): string => {
      if (!mounted) return defaultValue || key
      const translation = translations[language as Language][key as keyof typeof translations['es']]
      return translation || defaultValue || key
    },
    [language, mounted]
  )

  return { language, t, mounted }
}
